{"name": "test_login_password_error_case", "status": "broken", "statusDetails": {"message": "TypeError: login() takes 2 positional arguments but 3 were given", "trace": "self = <PrimarySelenium.case.login.test_login_case.TestLoginCase object at 0x03DF3448>, init_login = <bussiness.login_bussiness.LoginBussiness object at 0x03DD6670>\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures(\"init_driver\")\n    def test_login_password_error_case(self, init_login):\n    \n>       init_login.login(\"13544989573\", \"111111\")\nE       TypeError: login() takes 2 positional arguments but 3 were given\n\ncase\\login\\test_login_case.py:24: TypeError"}, "attachments": [{"name": "log", "source": "6d4f46e3-c8a9-4dfc-b695-c70aee2e03d1-attachment.txt", "type": "text/plain"}], "start": 1597502586685, "stop": 1597502586685, "uuid": "516bcd24-39a6-4d66-a5d4-0aa392bca653", "historyId": "8c75e61dfeaf40e00fbf3596d8f857c6", "testCaseId": "e31b71ea53c9108f5a105705e791d0a6", "fullName": "case.login.test_login_case.TestLoginCase#test_login_password_error_case", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "case.login"}, {"name": "suite", "value": "test_login_case"}, {"name": "subSuite", "value": "TestLoginCase"}, {"name": "host", "value": "FYYX-2019VXOSDQ"}, {"name": "thread", "value": "21428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.login.test_login_case"}]}