{"uuid": "37702489-1e35-4ec5-b920-a7281d7a011c", "children": ["9bd19f25-2c87-45bb-897f-8cfcb1e84a44"], "befores": [{"name": "init_search", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: missing 'cookie'\n  (Session info: chrome=84.0.4147.105)\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\pyProject\\PrimarySelenium\\case\\conftest.py\", line 66, in init_search\n    init_driver.set_cookies()\n  File \"D:\\pyProject\\PrimarySelenium\\base\\basepage.py\", line 369, in set_cookies\n    self.driver.add_cookie(cookie)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 894, in add_cookie\n    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1597399897102, "stop": 1597399898110}], "start": 1597399897102, "stop": 1597399899025}