{"name": "test_login_password_error_case", "status": "broken", "statusDetails": {"message": "NameError: name 'login' is not defined", "trace": "self = <PrimarySelenium.case.login.test_login_case.TestLoginCase object at 0x03CFED00>, init_login = <bussiness.login_bussiness.LoginBussiness object at 0x03CFECD0>\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures(\"init_driver\")\n    def test_login_password_error_case(self, init_login):\n    \n        init_login.login_eshop(\"13544989573\", \"111111\")\n>       assert init_login.check_login_fail() == False\n\ncase\\login\\test_login_case.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <bussiness.login_bussiness.LoginBussiness object at 0x03CFECD0>\n\n    def check_login_fail(self):\n>       if login.get_login_fail_tips() == \"用户名或密码错误\":\nE       NameError: name 'login' is not defined\n\nbussiness\\login_bussiness.py:21: NameError"}, "attachments": [{"name": "log", "source": "0cf83b50-a47d-4d39-b8d2-757a7bce9316-attachment.txt", "type": "text/plain"}], "start": 1597502947201, "stop": 1597502948202, "uuid": "41e967c0-06b6-4d75-9774-10cb05b030f4", "historyId": "8c75e61dfeaf40e00fbf3596d8f857c6", "testCaseId": "e31b71ea53c9108f5a105705e791d0a6", "fullName": "case.login.test_login_case.TestLoginCase#test_login_password_error_case", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "case.login"}, {"name": "suite", "value": "test_login_case"}, {"name": "subSuite", "value": "TestLoginCase"}, {"name": "host", "value": "FYYX-2019VXOSDQ"}, {"name": "thread", "value": "21472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.login.test_login_case"}]}